image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - build

build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:latest" -f VK/simulation/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:latest"