name: CI

on:
  push:
    branches:
      - main
      - study-1

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.VK_TOKEN }}" | docker login ghcr.io -u ${{ secrets.VK_USERNAME }} --password-stdin

    - name: Cache renv cache directory
      uses: actions/cache@v2
      with:
        path: renv_cache
        key: ${{ runner.os }}-renv-cache-${{ hashFiles('VK/simulation/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-cache-

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.VK_USERNAME }}/my-simulation:latest -f VK/simulation/Dockerfile .
        docker push ghcr.io/${{ secrets.VK_USERNAME }}/my-simulation:latest

    - name: Run simulation in Docker container
      run: |
        docker run --rm -v $(pwd)/VK/simulation/results:/home/rstudio/simulation/results ghcr.io/${{ secrets.VK_USERNAME }}/my-simulation:latest

    - name: Check logs and results
      run: |
        cat VK/simulation/results/simulation.log
        ls -lh VK/simulation/results/simulation_results.rda

    - name: Configure Git for pushing changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push results
      run: |
        cd VK/simulation/results
        git add simulation_results.rda
        git commit -m "Add simulation results"
        git push origin study-1
      env:
        GITHUB_TOKEN: ${{ secrets.VK_TOKEN }}