name: CI

on:
  push:
    branches:
      - main
      - study-1

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.VK_TOKEN }}" | docker login ghcr.io -u ${{ secrets.VK_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.VK_USERNAME }}/my-simulation:latest -f VK/simulation/Dockerfile .
        docker push ghcr.io/${{ secrets.VK_USERNAME }}/my-simulation:latest
