name: Release QMD and PDF to Zenodo

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: latest

    - name: Install TinyTeX
      run: |
        sudo apt-get install -y ghostscript
        wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
        export PATH=$PATH:/home/runner/.TinyTeX/bin/x86_64-linux
        sudo apt-get install -y texlive-xetex

    - name: Render QMD to PDF
      run: |
        export PATH=$PATH:/home/runner/.TinyTeX/bin/x86_64-linux
        quarto render VK/preregistration.qmd --to pdf

    - name: Create release artifacts
      run: |
        mkdir release
        cp VK/preregistration.qmd release/
        cp VK/preregistration.pdf release/

    - name: Upload Release Assets
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts
        path: release/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download release artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-artifacts

    - name: Upload to Zenodo
      env:
        ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODOTOKEN }}
      run: |
        # Create a new deposition
        deposition_id=$(curl -s -H "Authorization: Bearer $ZENODOTOKEN" -H "Content-Type: application/json" -d '{"metadata":{"title": "Preregistration Document", "upload_type": "publication", "description": "This is the preregistration document for the VK project.", "creators": [{"name": "Valentin Kriegmair", "affiliation": "Your Affiliation"}]}}' https://zenodo.org/api/deposit/depositions | jq -r .id)

        # Upload files
        curl -H "Authorization: Bearer $ZENODOTOKEN" -F "file=@release/preregistration.qmd" https://zenodo.org/api/deposit/depositions/$deposition_id/files
        curl -H "Authorization: Bearer $ZENODOTOKEN" -F "file=@release/preregistration.pdf" https://zenodo.org/api/deposit/depositions/$deposition_id/files

        # Publish the deposition
        curl -H "Authorization: Bearer $ZENODOTOKEN" -X POST https://zenodo.org/api/deposit/depositions/$deposition_id/actions/publish
