name: Test QMD to PDF Rendering

on:
  push:
    branches:
      - prereg/vk # Trigger on push to the test-render branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: latest

    - name: Install TinyTeX
      run: |
        sudo apt-get install -y ghostscript
        wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
        export PATH=$PATH:/home/runner/.TinyTeX/bin/x86_64-linux
        sudo apt-get install -y texlive-xetex

    - name: Render QMD to PDF
      run: |
        export PATH=$PATH:/home/runner/.TinyTeX/bin/x86_64-linux
        quarto render VK/preregistration.qmd --to pdf

    - name: Create release artifacts
      run: |
        mkdir release
        cp VK/preregistration.qmd release/
        cp VK/preregistration.pdf release/

    - name: Upload Release Assets
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts
        path: release/
